// design-system/output/svelte/src/components/FormError.svelte
<script context='module' lang='ts'>
      type FormErrorProps = {
errors: ErrorMessage[];
}

    </script>
    

    
<script lang='ts'>




  import  { t } from '../utils/i18n';
import type { ErrorMessage } from '../types';





    export let errors: FormErrorProps['errors'];




    $: items = () => {
return (errors ?? []).map(e => ({
  key: e.key,
  text: t(e.key, e.vars)
}));
};
$: prefix = () => {
return (errors ?? []).length > 1 ? '- ' : '';
};













  </script>


{#if items().length > 0 }
<div  class="rdp-form-error"  role="alert"  aria-live="polite" >
{#each items() as item }
<p  class="rdp-form-error__item" >{prefix()}{item.text}</p>
{/each}
</div>


{/if}

// design-system/output/vue/src/components/FormError.vue
<template>
  <template v-if="items.length > 0">
    <div class="rdp-form-error" role="alert" aria-live="polite">
      <template :key="index" v-for="(item, index) in items">
        <p class="rdp-form-error__item">
          {{ prefix }}{{ item.text }}
        </p> </template
      >
    </div>
  </template>
</template>

<script setup lang="ts">
import { computed } from "vue";

import { t } from "../utils/i18n";
import type { ErrorMessage } from "../types";

type FormErrorProps = {
  errors: ErrorMessage[];
};

const props = defineProps<FormErrorProps>();

const items = computed(() => {
  return (props.errors ?? []).map((e) => ({
    key: e.key,
    text: t(e.key, e.vars),
  }));
});
const prefix = computed(() => {
  return (props.errors ?? []).length > 1 ? "- " : "";
});
</script>
