// design-system/output/react/src/components/Sidebar.tsx
import * as React from "react";

type ListItem = {
  id: string;
  label: string;
};
type SidebarProps = {
  lists?: ListItem[];
  selectedListId?: string;
  selectedDate: Date;
  yearRange: {
    min: number;
    max: number;
  };
  minDate?: Date;
  locale?: Locale;
  onListSelect?: (id: string) => void;
  onDateSelect?: (date: Date) => void;
  onLegalNoticeClick?: () => void;
  onTermsOfServiceClick?: () => void;
  onContactClick?: () => void;
  onSupportClick?: () => void;
  onSourcesClick?: () => void;
  onDiscuterClick?: () => void;
};
import Calendar from "./Calendar";
import BannerAbout from "./BannerAbout";
import type { Locale } from "../utils/i18n";

function Sidebar(props: SidebarProps) {
  return (
    <aside className="rdp-sidebar">
      <Calendar
        selectedDate={props.selectedDate}
        locale={props.locale}
        yearRange={props.yearRange}
        minDate={props.minDate}
        onSelect={(d) => props.onDateSelect?.(d)}
      />
      <BannerAbout
        onLegalNoticeClick={(event) => props.onLegalNoticeClick()}
        onTermsOfServiceClick={(event) => props.onTermsOfServiceClick()}
        onContactClick={(event) => props.onContactClick()}
        onSupportClick={(event) => props.onSupportClick()}
        onSourcesClick={(event) => props.onSourcesClick()}
        onDiscuterClick={(event) => props.onDiscuterClick()}
      />
      <style>{`
        .rdp-sidebar {
          width: 336px;
          max-width: 100%;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          gap: var(--separation-2);
          min-width: 0;
        }
        .rdp-sidebar > * { min-width: 0; max-width: 100%; box-sizing: border-box; }
      `}</style>
    </aside>
  );
}

export default Sidebar;

// design-system/output/vue/src/components/Sidebar.vue
<template>
  <aside class="rdp-sidebar">
    <Calendar
      :selectedDate="selectedDate"
      :locale="locale"
      :yearRange="yearRange"
      :minDate="minDate"
      :onSelect="(d) => onDateSelect?.(d)"
    ></Calendar
    ><BannerAbout
      :onLegalNoticeClick="(event) => onLegalNoticeClick()"
      :onTermsOfServiceClick="(event) => onTermsOfServiceClick()"
      :onContactClick="(event) => onContactClick()"
      :onSupportClick="(event) => onSupportClick()"
      :onSourcesClick="(event) => onSourcesClick()"
      :onDiscuterClick="(event) => onDiscuterClick()"
    ></BannerAbout
    ><component :is="'style'">{{
      `
        .rdp-sidebar {
          width: 336px;
          max-width: 100%;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          gap: var(--separation-2);
          min-width: 0;
        }
        .rdp-sidebar > * { min-width: 0; max-width: 100%; box-sizing: border-box; }
      `
    }}</component>
  </aside>
</template>

<script setup lang="ts">
import Calendar from "./Calendar.vue";
import BannerAbout from "./BannerAbout.vue";
import type { Locale } from "../utils/i18n";

type ListItem = {
  id: string;
  label: string;
};
type SidebarProps = {
  lists?: ListItem[];
  selectedListId?: string;
  selectedDate: Date;
  yearRange: {
    min: number;
    max: number;
  };
  minDate?: Date;
  locale?: Locale;
  onListSelect?: (id: string) => void;
  onDateSelect?: (date: Date) => void;
  onLegalNoticeClick?: () => void;
  onTermsOfServiceClick?: () => void;
  onContactClick?: () => void;
  onSupportClick?: () => void;
  onSourcesClick?: () => void;
  onDiscuterClick?: () => void;
};

const props = defineProps<SidebarProps>();
</script>
