// design-system/output/svelte/src/components/SourcesPage.svelte
<script lang='ts'>





























</script>

<article  class="rdp-sources-page" ><h1 >Sources des brèves</h1><p >
    Les sources des brèves de publications<a  class="rdp-sources-page__internal-link"  href="#rdp-sources-page-footnote" >
      triées par popularité
    </a>
    en fin de chaque journée proviennent des comptes Bluesky de médias Français.
  </p><p  id="rdp-sources-page-footnote"  class="rdp-sources-page__footnote" >
    La popularité est déduite des partages des publications depuis Bluesky.
  </p></article>

// design-system/output/vue/src/components/SourcesPage.vue
<template>
  <article class="rdp-sources-page">
    <h1>Sources des brèves</h1>
    <p>
      Les sources des brèves de publications<a
        class="rdp-sources-page__internal-link"
        href="#rdp-sources-page-footnote"
      >
        triées par popularité
      </a>
      en fin de chaque journée proviennent des comptes Bluesky de médias
      Français.
    </p>
    <p id="rdp-sources-page-footnote" class="rdp-sources-page__footnote">
      La popularité est déduite des partages des publications depuis Bluesky.
    </p>
    
  </article>
</template>
