// design-system/output/vue/src/components/IntroCard.vue
<template>
  <article class="rdp-intro-card">
    <header class="rdp-intro-card__header">
      <span class="rdp-intro-card__avatar" aria-hidden="true"
        ><Logo size="md" altKey="logo.alt" :showWordmark="false"></Logo></span
      ><span class="rdp-intro-card__author"
        ><strong>revue_2_presse</strong
        ><span class="rdp-intro-card__handle">@revue-de-presse.org</span></span
      >
    </header>
    <p class="rdp-intro-card__body">
      Revue-de-presse.org est un projet citoyen indépendant qui s'adresse à
      toute personne curieuse de l'actualité et de l'influence des médias sur
      l'opinion.
    </p>
    
  </article>
</template>

<script setup lang="ts">
import Logo from "./Logo.vue";
</script>

// design-system/output/svelte/src/components/IntroCard.svelte
<script lang='ts'>




import  Logo from './Logo.svelte';
























</script>

<article  class="rdp-intro-card" ><header  class="rdp-intro-card__header" ><span  class="rdp-intro-card__avatar"  aria-hidden="true" ><Logo  size="md"  altKey="logo.alt"  showWordmark={false} ></Logo></span><span  class="rdp-intro-card__author" ><strong >revue_2_presse</strong><span  class="rdp-intro-card__handle" >@revue-de-presse.org</span></span></header><p  class="rdp-intro-card__body" >
    Revue-de-presse.org est un projet citoyen indépendant qui s'adresse à
    toute personne curieuse de l'actualité et de l'influence des médias sur
    l'opinion.
  </p></article>
