// design-system/output/react/src/components/DateGrid.tsx
"use client";
import * as React from "react";
import { useState } from "react";

type DateGridProps = {
  year: number;
  month: number; // 0..11
  selectedDate?: Date;
  locale?: Locale;
  onSelect?: (date: Date) => void;
};
import { t } from "../utils/i18n";
import type { Locale } from "../utils/i18n";

function DateGrid(props: DateGridProps) {
  const [weekdays, setWeekdays] = useState(() => [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ]);

  function rows() {
    const first = new Date(props.year, props.month, 1);
    const offset = (first.getDay() + 6) % 7;
    const start = new Date(props.year, props.month, 1 - offset);
    const all = Array.from(
      {
        length: 42,
      },
      (_, i) =>
        new Date(start.getFullYear(), start.getMonth(), start.getDate() + i)
    );
    return [0, 1, 2, 3, 4, 5].map((row) => all.slice(row * 7, row * 7 + 7));
  }

  function isSelected(d: Date) {
    const sel = props.selectedDate;
    return (
      !!sel &&
      sel.getFullYear() === d.getFullYear() &&
      sel.getMonth() === d.getMonth() &&
      sel.getDate() === d.getDate()
    );
  }

  function isFuture(d: Date) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const cell = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    return cell.getTime() > today.getTime();
  }

  return (
    <table className="rdp-date-grid" role="grid">
      <thead>
        <tr>
          {weekdays?.map((w) => (
            <th scope="col" className="rdp-date-grid__weekday">
              {t(
                `calendar.weekdays.short.${w}`,
                undefined,
                props.locale ?? "fr-FR"
              )}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows()?.map((row) => (
          <tr>
            {row?.map((d) => (
              <td
                role="gridcell"
                aria-selected={isSelected(d) ? "true" : "false"}
                aria-disabled={isFuture(d) ? "true" : undefined}
                data-other-month={
                  d.getMonth() !== props.month ? "true" : undefined
                }
                data-future={isFuture(d) ? "true" : undefined}
                className={`rdp-date-grid__cell${
                  isSelected(d) ? " rdp-date-grid__cell--selected" : ""
                }`}
                onClick={(event) => {
                  if (!isFuture(d)) props.onSelect?.(d);
                }}
              >
                {d.getDate()}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
      <style>{`
        .rdp-date-grid {
          width: 100%;
          table-layout: fixed;
          border-collapse: separate;
          border-spacing: 2px;
          font-family: 'Roboto', sans-serif;
          font-size: var(--font-size-calendar-month-day-cell);
        }
        .rdp-date-grid__weekday {
          font-weight: normal;
          font-size: var(--font-size-calendar-month-day);
          color: var(--color-brand);
          padding: 4px 0;
          text-align: center;
        }
        .rdp-date-grid__cell {
          padding: 6px 0;
          border: 1px solid var(--color-border);
          border-radius: var(--radius-selectable);
          color: var(--color-content-text);
          background: var(--color-background-future-date);
          cursor: pointer;
          text-align: center;
        }
        .rdp-date-grid__cell[data-other-month="true"] {
          background: var(--color-background-other-month);
          color: var(--color-light-grey);
        }
        .rdp-date-grid__cell[data-future="true"] {
          color: var(--color-light-grey);
          background: var(--color-background-other-month);
          cursor: not-allowed;
        }
        .rdp-date-grid__cell--selected {
          background: var(--color-brand);
          color: var(--color-white);
          border-color: var(--color-brand);
        }
      `}</style>
    </table>
  );
}

export default DateGrid;

// design-system/output/solid/src/components/DateGrid.tsx
import { For, createSignal, createMemo } from "solid-js";

type DateGridProps = {
  year: number;
  month: number; // 0..11
  selectedDate?: Date;
  locale?: Locale;
  onSelect?: (date: Date) => void;
};

import { t } from "../utils/i18n";
import type { Locale } from "../utils/i18n";

function DateGrid(props: DateGridProps) {
  const [weekdays, setWeekdays] = createSignal([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ]);

  const rows = createMemo(() => {
    const first = new Date(props.year, props.month, 1);
    const offset = (first.getDay() + 6) % 7;
    const start = new Date(props.year, props.month, 1 - offset);
    const all = Array.from(
      {
        length: 42,
      },
      (_, i) =>
        new Date(start.getFullYear(), start.getMonth(), start.getDate() + i)
    );
    return [0, 1, 2, 3, 4, 5].map((row) => all.slice(row * 7, row * 7 + 7));
  });

  function isSelected(d: Date) {
    const sel = props.selectedDate;
    return (
      !!sel &&
      sel.getFullYear() === d.getFullYear() &&
      sel.getMonth() === d.getMonth() &&
      sel.getDate() === d.getDate()
    );
  }

  function isFuture(d: Date) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const cell = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    return cell.getTime() > today.getTime();
  }

  return (
    <>
      <table class="rdp-date-grid" role="grid">
        <thead>
          <tr>
            <For each={weekdays()}>
              {(w, _index) => {
                const index = _index();
                return (
                  <th class="rdp-date-grid__weekday" scope="col">
                    {t(
                      `calendar.weekdays.short.${w}`,
                      undefined,
                      props.locale ?? "fr-FR"
                    )}
                  </th>
                );
              }}
            </For>
          </tr>
        </thead>
        <tbody>
          <For each={rows()}>
            {(row, _index) => {
              const index = _index();
              return (
                <tr>
                  <For each={row}>
                    {(d, _index) => {
                      const index = _index();
                      return (
                        <td
                          class={`rdp-date-grid__cell${
                            isSelected(d)
                              ? " rdp-date-grid__cell--selected"
                              : ""
                          }`}
                          role="gridcell"
                          aria-selected={isSelected(d) ? "true" : "false"}
                          aria-disabled={isFuture(d) ? "true" : undefined}
                          data-other-month={
                            d.getMonth() !== props.month ? "true" : undefined
                          }
                          data-future={isFuture(d) ? "true" : undefined}
                          onClick={(event) => {
                            if (!isFuture(d)) props.onSelect?.(d);
                          }}
                        >
                          {d.getDate()}
                        </td>
                      );
                    }}
                  </For>
                </tr>
              );
            }}
          </For>
        </tbody>
        <style>{`
        .rdp-date-grid {
          width: 100%;
          table-layout: fixed;
          border-collapse: separate;
          border-spacing: 2px;
          font-family: 'Roboto', sans-serif;
          font-size: var(--font-size-calendar-month-day-cell);
        }
        .rdp-date-grid__weekday {
          font-weight: normal;
          font-size: var(--font-size-calendar-month-day);
          color: var(--color-brand);
          padding: 4px 0;
          text-align: center;
        }
        .rdp-date-grid__cell {
          padding: 6px 0;
          border: 1px solid var(--color-border);
          border-radius: var(--radius-selectable);
          color: var(--color-content-text);
          background: var(--color-background-future-date);
          cursor: pointer;
          text-align: center;
        }
        .rdp-date-grid__cell[data-other-month="true"] {
          background: var(--color-background-other-month);
          color: var(--color-light-grey);
        }
        .rdp-date-grid__cell[data-future="true"] {
          color: var(--color-light-grey);
          background: var(--color-background-other-month);
          cursor: not-allowed;
        }
        .rdp-date-grid__cell--selected {
          background: var(--color-brand);
          color: var(--color-white);
          border-color: var(--color-brand);
        }
      `}</style>
      </table>
    </>
  );
}

export default DateGrid;
