// design-system/packages/provider-solid/src/index.tsx
import { createContext, useContext, createSignal, type JSX, type ParentProps } from 'solid-js';
import { t as defaultT, setLocale as defaultSetLocale, type Locale } from '../../../src/utils/i18n';

type DSContext = {
  t: (k: string, vars?: Record<string, string | number>) => string;
  locale: () => Locale;
  setLocale: (l: Locale) => void;
};

const Ctx = createContext<DSContext>();

export function DesignSystemProvider(
  props: ParentProps<{ locale?: Locale; t?: DSContext['t'] }>
): JSX.Element {
  const [locale, setLocaleSignal] = createSignal<Locale>(props.locale ?? 'fr-FR');
  const ctx: DSContext = {
    t: props.t ?? ((k, v) => defaultT(k, v, locale())),
    locale,
    setLocale: (l) => {
      defaultSetLocale(l);
      setLocaleSignal(l);
    },
  };
  return <Ctx.Provider value={ctx}>{props.children}</Ctx.Provider>;
}

export function useDesignSystem(): DSContext {
  const v = useContext(Ctx);
  if (!v) {
    return { t: defaultT, locale: () => 'fr-FR', setLocale: defaultSetLocale };
  }
  return v;
}

// design-system/packages/provider-react/src/index.tsx
import React, { createContext, useContext, useState } from 'react';
import { t as defaultT, setLocale, type Locale } from '../../../src/utils/i18n';

type DSContext = {
  t: (key: string, vars?: Record<string, string | number>) => string;
  locale: Locale;
  setLocale: (l: Locale) => void;
};

const Ctx = createContext<DSContext | null>(null);

export function DesignSystemProvider({
  children,
  t,
  locale: initialLocale = 'fr-FR',
}: {
  children: React.ReactNode;
  t?: (key: string, vars?: Record<string, string | number>) => string;
  locale?: Locale;
}) {
  const [locale, _setLocale] = useState<Locale>(initialLocale);
  const value: DSContext = {
    t: t ?? ((key, vars) => defaultT(key, vars, locale)),
    locale,
    setLocale: (l) => {
      setLocale(l);
      _setLocale(l);
    },
  };
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useDesignSystem(): DSContext {
  const v = useContext(Ctx);
  if (!v) {
    return { t: defaultT, locale: 'fr-FR', setLocale };
  }
  return v;
}
